package com.se.ui.contact.supplier;

import com.se.database.entities.Employee;
import com.se.database.sql.SupplierSQL;
import com.se.ui.dashboard.DashboardView;
import static com.se.ui.dashboard.DashboardView.DesktopPane;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author RDA
 */
public class EditSupplierView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewSupplierUpdate
     */
    public EditSupplierView() {
        initComponents();
    }

    private Employee aEmp;
    private String name;
    private String company;
    private String nic;
    private String email;
    private String contact;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        ViewSupplierUpdate = new javax.swing.JPanel();
        lblSupplierID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblCompany = new javax.swing.JLabel();
        lblNic = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTelephone = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        lblSupplierIDShow = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtCompany = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtNic = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblTitleShow = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setClosable(true);
        setTitle("Edit Supplier");

        lblSupplierID.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblSupplierID.setText("Supplier ID");

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblName.setText("Name");

        lblCompany.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblCompany.setText("Company");

        lblNic.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblNic.setText("NIC");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblEmail.setText("E-mail");

        lblTelephone.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblTelephone.setText("Telephone");

        btnOk.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        lblSupplierIDShow.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtTelephone.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtTelephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelephoneKeyReleased(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        txtCompany.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCompanyKeyReleased(evt);
            }
        });

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        txtNic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNicKeyReleased(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblTitle.setText("Title");

        lblTitleShow.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout ViewSupplierUpdateLayout = new javax.swing.GroupLayout(ViewSupplierUpdate);
        ViewSupplierUpdate.setLayout(ViewSupplierUpdateLayout);
        ViewSupplierUpdateLayout.setHorizontalGroup(
            ViewSupplierUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewSupplierUpdateLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(ViewSupplierUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ViewSupplierUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(ViewSupplierUpdateLayout.createSequentialGroup()
                            .addGroup(ViewSupplierUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblEmail)
                                .addComponent(lblTelephone))
                            .addGap(91, 91, 91)
                            .addGroup(ViewSupplierUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEmail)
                                .addComponent(txtTelephone)))
                        .addGroup(ViewSupplierUpdateLayout.createSequentialGroup()
                            .addGroup(ViewSupplierUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSupplierID)
                                .addComponent(lblName)
                                .addComponent(lblCompany)
                                .addComponent(lblNic))
                            .addGroup(ViewSupplierUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ViewSupplierUpdateLayout.createSequentialGroup()
                                    .addGap(91, 91, 91)
                                    .addGroup(ViewSupplierUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblSupplierIDShow, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                                        .addComponent(txtName)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewSupplierUpdateLayout.createSequentialGroup()
                                    .addGap(89, 89, 89)
                                    .addGroup(ViewSupplierUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCompany, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                                        .addComponent(txtNic)))))
                        .addGroup(ViewSupplierUpdateLayout.createSequentialGroup()
                            .addComponent(lblTitle)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                            .addComponent(lblTitleShow, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        ViewSupplierUpdateLayout.setVerticalGroup(
            ViewSupplierUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewSupplierUpdateLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(ViewSupplierUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSupplierID)
                    .addComponent(lblSupplierIDShow, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ViewSupplierUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(lblTitleShow, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(ViewSupplierUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ViewSupplierUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewSupplierUpdateLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblCompany))
                    .addGroup(ViewSupplierUpdateLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(ViewSupplierUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewSupplierUpdateLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblNic))
                    .addGroup(ViewSupplierUpdateLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtNic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(ViewSupplierUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(ViewSupplierUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelephone)
                    .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnOk)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ViewSupplierUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ViewSupplierUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        txtAction();
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtCompanyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCompanyKeyReleased
        txtAction();
    }//GEN-LAST:event_txtCompanyKeyReleased

    private void txtNicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNicKeyReleased
        txtAction();
    }//GEN-LAST:event_txtNicKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        txtAction();
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtTelephoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelephoneKeyReleased
        txtAction();
    }//GEN-LAST:event_txtTelephoneKeyReleased

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if (btnOk.getText().equals("OK")) {
            SupplierView view = new SupplierView();
            this.dispose();
            DashboardView.DesktopPane.remove((Component) view);
            DashboardView.DesktopPane.add((Component) view);
            view.initializeView(aEmp);
            view.setLocation((int) ((DesktopPane.getSize().width - view.getSize().width) / 2), (int) ((DesktopPane.getSize().height - view.getSize().height) / 2));
            view.setVisible(true);
        } else {
            if (txtName.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Enter name");
                return;
            }

            if (txtCompany.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Enter company");
                return;
            }

            if (txtNic.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Enter NIC number");
                return;
            }
            Pattern nicp = Pattern.compile("(\\d{9}[V])*");
            Matcher m = nicp.matcher(txtNic.getText());
            if (!m.matches()) {
                JOptionPane.showMessageDialog(this, "Enter valid NIC number");
                return;
            }

            if (txtEmail.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Enter E-mail");
                return;
            }
            Pattern ep = Pattern.compile("(^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$)*", Pattern.CASE_INSENSITIVE);
            m = ep.matcher(txtEmail.getText());
            if (!m.matches()) {
                JOptionPane.showMessageDialog(this, "Enter valid E-mail");
                return;
            }

            if (txtTelephone.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Enter contact number");
                return;
            }
            Pattern pp = Pattern.compile("(\\d{10})*");
            m = pp.matcher(txtTelephone.getText());
            if (!m.matches()) {
                JOptionPane.showMessageDialog(this, "Enter valid contact number");
                return;
            }

            int input = JOptionPane.showConfirmDialog(this, "Do you want to change details of this supplier?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (input == JOptionPane.YES_OPTION) {
                pfAction();
            }
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void pfAction() {
        JPasswordField jpf = new JPasswordField();
        int action = JOptionPane.showConfirmDialog(this, jpf, "Enter your Password", JOptionPane.OK_CANCEL_OPTION);
        if (action == 0) {
            if (aEmp.getPassword().equals(new String(jpf.getPassword()))) {
                SupplierSQL.updateSupplier(Integer.parseInt(lblSupplierIDShow.getText()), txtName.getText(), txtCompany.getText(), txtNic.getText(), txtEmail.getText(), txtTelephone.getText());
                JOptionPane.showMessageDialog(this, "Details Successfully Updated!");
                SupplierView view = new SupplierView();
                this.dispose();
                DashboardView.DesktopPane.remove((Component) view);
                DashboardView.DesktopPane.add((Component) view);
                view.initializeView(aEmp);
                view.setLocation((int) ((DesktopPane.getSize().width - view.getSize().width) / 2), (int) ((DesktopPane.getSize().height - view.getSize().height) / 2));
                view.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect Password");
                pfAction();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ViewSupplierUpdate;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNic;
    private javax.swing.JLabel lblSupplierID;
    private javax.swing.JLabel lblSupplierIDShow;
    private javax.swing.JLabel lblTelephone;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleShow;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextField txtTelephone;
    // End of variables declaration//GEN-END:variables

    void initializeView(Employee aEmp, int id, String title, String name, String company, String nic, String email, String phone) {
        this.aEmp = aEmp;
        this.name = name;
        this.company = company;
        this.nic = nic;
        this.email = email;
        this.contact = phone;

        lblSupplierIDShow.setText(String.valueOf(id));
        lblTitleShow.setText(title);
        txtName.setText(name);
        txtCompany.setText(company);
        txtNic.setText(nic);
        txtEmail.setText(email);
        txtTelephone.setText(phone);
    }

    private void txtAction() {
        if (txtName.getText().equals(name) && txtCompany.getText().equals(company) && txtNic.getText().equals(nic) && txtEmail.getText().equals(email) && txtTelephone.getText().equals(contact)) {
            btnOk.setText("OK");
        } else {
            btnOk.setText("Update");
        }
    }

}
