package com.se.ui.contact.supplier;

import com.se.database.entities.Employee;
import com.se.database.sql.SupplierSQL;
import com.se.ui.dashboard.DashboardView;
import static com.se.ui.dashboard.DashboardView.DesktopPane;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author RDA
 */
public class NewSupplierView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewSupplierNew
     */
    public NewSupplierView() {
        initComponents();
    }

    private Employee aEmp;
    //private String aRole;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SupplierNew = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblCompany = new javax.swing.JLabel();
        lblNic = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtCompany = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        txtNic = new javax.swing.JTextField();
        cmbTitle = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("New Supplier");

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblName.setText("Name");

        lblCompany.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblCompany.setText("Company");

        lblNic.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblNic.setText("NIC");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblEmail.setText("E-mail");

        lblTel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblTel.setText("Telephone");

        txtCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyActionPerformed(evt);
            }
        });

        btnInsert.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnInsert.setText("Add");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        cmbTitle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select the title>", "Mr.", "Mrs.", "Ms." }));
        cmbTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTitleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("Title");

        javax.swing.GroupLayout SupplierNewLayout = new javax.swing.GroupLayout(SupplierNew);
        SupplierNew.setLayout(SupplierNewLayout);
        SupplierNewLayout.setHorizontalGroup(
            SupplierNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupplierNewLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(SupplierNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInsert)
                    .addGroup(SupplierNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SupplierNewLayout.createSequentialGroup()
                            .addGroup(SupplierNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblEmail)
                                .addComponent(lblTel))
                            .addGap(52, 52, 52)
                            .addGroup(SupplierNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                .addComponent(txtPhone)))
                        .addGroup(SupplierNewLayout.createSequentialGroup()
                            .addGroup(SupplierNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCompany)
                                .addComponent(lblName)
                                .addComponent(lblNic)
                                .addComponent(jLabel1))
                            .addGap(56, 56, 56)
                            .addGroup(SupplierNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                                .addComponent(txtCompany, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNic, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        SupplierNewLayout.setVerticalGroup(
            SupplierNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupplierNewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SupplierNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(SupplierNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SupplierNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompany)
                    .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SupplierNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNic)
                    .addComponent(txtNic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SupplierNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SupplierNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTel)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnInsert)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SupplierNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SupplierNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanyActionPerformed

    private void cmbTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTitleActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        int title1 = cmbTitle.getSelectedIndex();
        String name = txtName.getText().trim();
        String company = txtCompany.getText().trim();
        String nic = txtNic.getText().trim();
        String email = txtEmail.getText().trim();
        String phone = txtPhone.getText().trim();

        String strTitle;
        if (title1 == 0) {
            JOptionPane.showMessageDialog(this, "Select the title");
            return;
        } else {
            strTitle = cmbTitle.getSelectedItem().toString();
        }

        if (name.equals("")) {
            JOptionPane.showMessageDialog(this, "Enter name");
            return;
        }

        if (company.equals("")) {
            JOptionPane.showMessageDialog(this, "Enter company");
            return;
        }

        if (nic.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter NIC number");
            return;
        }
        Pattern nicp = Pattern.compile("(\\d{9}[V])*");
        Matcher m = nicp.matcher(nic);
        if (!m.matches()) {
            JOptionPane.showMessageDialog(this, "Enter valid NIC number");
            return;
        }

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter E-mail");
            return;
        }
        Pattern ep = Pattern.compile("(^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$)*", Pattern.CASE_INSENSITIVE);
        m = ep.matcher(email);
        if (!m.matches()) {
            JOptionPane.showMessageDialog(this, "Enter valid E-mail");
            return;
        }

        if (phone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter contact number");
            return;
        }
        Pattern pp = Pattern.compile("(\\d{10})*");
        m = pp.matcher(phone);
        if (!m.matches()) {
            JOptionPane.showMessageDialog(this, "Enter valid contact number");
            return;
        }

        SupplierSQL.addSupplier(0, strTitle, name, company, nic, email, phone);
        JOptionPane.showMessageDialog(this, "Supplier added successfully!", "", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        SupplierView sView = new SupplierView();
        DashboardView.DesktopPane.add((Component) sView);
        sView.initializeView(aEmp);
        sView.setLocation((int) ((DesktopPane.getSize().width - sView.getSize().width) / 2), (int) ((DesktopPane.getSize().height - sView.getSize().height) / 2));
        sView.setVisible(true);
    }//GEN-LAST:event_btnInsertActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SupplierNew;
    private javax.swing.JButton btnInsert;
    private javax.swing.JComboBox<String> cmbTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNic;
    private javax.swing.JLabel lblTel;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables

    public void initializeView(Employee aEmp) {
        this.aEmp = aEmp;
        //this.aRole = aEmp.getRole();
    }
}
