/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.se.ui.purchase;

import com.se.database.entities.Items;
import com.se.database.entities.TransactionHasItem;
import com.se.database.entities.GrnHasItem;
import com.se.database.sql.ItemSQL;
import com.se.database.sql.TransactionHasItemSQL;
import com.se.database.sql.GrnHasItemsSQL;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BHARATHA
 */
public class GRNItemsView extends javax.swing.JInternalFrame {

    private int grnID;
    private String emp;
    private String sup;
    private String date;
    private String total;
    private String note;

    private DefaultTableModel dtmTrans;
    private List<GrnHasItem> list;
    private List<Items> Itmlist;

    public GRNItemsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGRN = new javax.swing.JTable();
        lblGRNId = new javax.swing.JLabel();
        lblGRNIdShow = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblDateShow = new javax.swing.JLabel();
        lblSupplier = new javax.swing.JLabel();
        lblSupplierShow = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblTotalView = new javax.swing.JLabel();
        lblEmployer = new javax.swing.JLabel();
        lblEmployerShow = new javax.swing.JLabel();
        lblNote = new javax.swing.JLabel();
        lblNoteView = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Goods Received Note");

        tblGRN.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblGRN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category", "Item", "Qty", "Unit Price", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblGRN);
        if (tblGRN.getColumnModel().getColumnCount() > 0) {
            tblGRN.getColumnModel().getColumn(0).setMinWidth(0);
            tblGRN.getColumnModel().getColumn(0).setPreferredWidth(200);
            tblGRN.getColumnModel().getColumn(0).setMaxWidth(200);
            tblGRN.getColumnModel().getColumn(2).setMinWidth(0);
            tblGRN.getColumnModel().getColumn(2).setPreferredWidth(80);
            tblGRN.getColumnModel().getColumn(2).setMaxWidth(80);
            tblGRN.getColumnModel().getColumn(3).setMinWidth(0);
            tblGRN.getColumnModel().getColumn(3).setPreferredWidth(160);
            tblGRN.getColumnModel().getColumn(3).setMaxWidth(160);
            tblGRN.getColumnModel().getColumn(4).setMinWidth(0);
            tblGRN.getColumnModel().getColumn(4).setPreferredWidth(160);
            tblGRN.getColumnModel().getColumn(4).setMaxWidth(160);
        }

        lblGRNId.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblGRNId.setText("GRN ID :");

        lblGRNIdShow.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblDate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblDate.setText("Date :");

        lblDateShow.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblSupplier.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblSupplier.setText("Supplier :");

        lblSupplierShow.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblTotal.setText("Total");

        lblTotalView.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblEmployer.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblEmployer.setText("Employer :");

        lblEmployerShow.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblNote.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblNote.setText("Note :");

        lblNoteView.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblNoteView.setText("Note");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotal)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalView, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNote)
                                    .addComponent(lblGRNId))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblGRNIdShow, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)
                                        .addComponent(lblDate)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDateShow, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblSupplierShow, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblEmployer)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblEmployerShow, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(lblNoteView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblGRNId)
                        .addComponent(lblGRNIdShow, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSupplier)
                        .addComponent(lblDate)
                        .addComponent(lblDateShow, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblSupplierShow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmployer)
                    .addComponent(lblEmployerShow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNote)
                    .addComponent(lblNoteView))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(lblTotalView, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDateShow;
    private javax.swing.JLabel lblEmployer;
    private javax.swing.JLabel lblEmployerShow;
    private javax.swing.JLabel lblGRNId;
    private javax.swing.JLabel lblGRNIdShow;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblNoteView;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblSupplierShow;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalView;
    private javax.swing.JTable tblGRN;
    // End of variables declaration//GEN-END:variables

    public void initializeView(int INgrnID, String INempID, String INsupID, String note, String dt, String tol) {
        this.grnID = INgrnID;
        this.emp = INempID;
        this.sup = INsupID;
        
        if(note.equals(""))
            this.note = "No Special Note";
        else
            this.note = note;
        
        this.date = dt;
        this.total = tol;
        this.lblGRNIdShow.setText(String.valueOf(grnID));
        this.lblEmployerShow.setText(emp);
        this.lblSupplierShow.setText(sup);
        this.lblDateShow.setText(dt);
        this.lblTotalView.setText(tol);
        this.lblNoteView.setText(this.note);

        list = GrnHasItemsSQL.getAllItems();
        Itmlist = ItemSQL.getAllItems();
        setDtmTrans();
        list.forEach(item -> {
            if (grnID == item.getGrn_grn_id()) {

                String ItemName = "";
                String catagory = "";
                double UPrice = 0;
                for (Items itm : Itmlist) {
                    if (itm.getItem_id() == item.getItem_item_id()) {
                        ItemName = itm.getItem_Name();
                        UPrice = itm.getUnit_price();
                        catagory = itm.getCategory();
                    }
                }
                double amount = UPrice * item.getItem_qty();
                dtmTrans.addRow(new Object[]{catagory, ItemName, item.getItem_qty(), String.format("%.2f", UPrice), String.format("%.2f", amount)});
            }

        });

    }

    private void setDtmTrans() {
        dtmTrans = (DefaultTableModel) this.tblGRN.getModel();
        dtmTrans.getDataVector().removeAllElements();
        dtmTrans.fireTableDataChanged();
    }

}
