/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.se.ui.purchase;

import com.se.database.entities.Items;
import com.se.database.sql.ItemSQL;
import com.se.database.sql.GrnSQL;
import com.se.database.sql.GrnHasItemsSQL;
import com.se.database.sql.SupplierSQL;
import com.se.ui.utils.Report;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.type.OrientationEnum;

/**
 *
 * @author Gayani
 */
public class NewGRNView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ItemListView
     */
    public NewGRNView() {
        initComponents();
    }

    private DefaultTableModel dtmItems;
    private DefaultTableModel dtmCart;
    private List<Items> list;
    private ArrayList<Object> items;
    private int qty;
    private double total;
    private int id;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblItem = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox<>();
        lblCategory = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItemList = new javax.swing.JTable();
        spinnerQty = new javax.swing.JSpinner();
        lblQty = new javax.swing.JLabel();
        btnAddToCart = new javax.swing.JButton();
        pannelCart = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        btnClear = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnCheckout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTQnty = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtNote = new javax.swing.JTextField();
        lblSupplier = new javax.swing.JLabel();
        cmbSupplier = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("New Goods Received Note");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblItem.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem.setText("Item");
        jPanel1.add(lblItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 33, 20));

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdKeyReleased(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 240, 23));

        cmbCategory.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Categories" }));
        cmbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoryActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 240, -1));

        lblCategory.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblCategory.setText("Category");
        jPanel1.add(lblCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        tblItemList.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblItemList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Unit Price", "Qty"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblItemList.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblItemList);
        if (tblItemList.getColumnModel().getColumnCount() > 0) {
            tblItemList.getColumnModel().getColumn(1).setMinWidth(0);
            tblItemList.getColumnModel().getColumn(1).setPreferredWidth(90);
            tblItemList.getColumnModel().getColumn(1).setMaxWidth(90);
            tblItemList.getColumnModel().getColumn(2).setMinWidth(0);
            tblItemList.getColumnModel().getColumn(2).setPreferredWidth(60);
            tblItemList.getColumnModel().getColumn(2).setMaxWidth(60);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 350, 140));

        spinnerQty.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        spinnerQty.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerQtyStateChanged(evt);
            }
        });
        jPanel1.add(spinnerQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 50, -1));

        lblQty.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblQty.setText("Qty");
        jPanel1.add(lblQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 30, 20));

        btnAddToCart.setText("Add to Cart");
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 130, -1));

        pannelCart.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 120, 212)), "Cart", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12))); // NOI18N

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category", "Item", "Unit Price (Rs)", "Qty"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCart.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblCart);
        if (tblCart.getColumnModel().getColumnCount() > 0) {
            tblCart.getColumnModel().getColumn(0).setMinWidth(0);
            tblCart.getColumnModel().getColumn(0).setPreferredWidth(200);
            tblCart.getColumnModel().getColumn(0).setMaxWidth(200);
            tblCart.getColumnModel().getColumn(2).setMinWidth(0);
            tblCart.getColumnModel().getColumn(2).setPreferredWidth(160);
            tblCart.getColumnModel().getColumn(2).setMaxWidth(160);
            tblCart.getColumnModel().getColumn(3).setMinWidth(0);
            tblCart.getColumnModel().getColumn(3).setPreferredWidth(90);
            tblCart.getColumnModel().getColumn(3).setMaxWidth(90);
        }

        btnClear.setText("Clear All");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnCheckout.setText("Checkout");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Total Quantity");

        lblTQnty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTQnty.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTQnty.setText("0");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Sub Total");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("Rs. 0.0");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 120, 212), 1, true), "Special Notes"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNote)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNote, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pannelCartLayout = new javax.swing.GroupLayout(pannelCart);
        pannelCart.setLayout(pannelCartLayout);
        pannelCartLayout.setHorizontalGroup(
            pannelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelCartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pannelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelCartLayout.createSequentialGroup()
                        .addGroup(pannelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pannelCartLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTQnty, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pannelCartLayout.createSequentialGroup()
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pannelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCheckout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pannelCartLayout.setVerticalGroup(
            pannelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelCartLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pannelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnRemove)
                    .addComponent(btnCheckout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pannelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTQnty, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel1.add(pannelCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 700, 460));

        lblSupplier.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblSupplier.setText("Supplier");
        jPanel1.add(lblSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        cmbSupplier.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmbSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select the Supplier>" }));
        jPanel1.add(cmbSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed
        setDtmItems();
        resetTxt();
        cmbCategoryAction(cmbCategory.getSelectedIndex());
    }//GEN-LAST:event_cmbCategoryActionPerformed

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        tblItemAction();

    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void spinnerQtyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerQtyStateChanged
        if ((int) spinnerQty.getValue() < 0) {
            spinnerQty.setValue(0);
        }
    }//GEN-LAST:event_spinnerQtyStateChanged

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        if (tblCart.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Cart is already empty!", "", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int input = JOptionPane.showConfirmDialog(this, "Do you want to clear the cart?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (input == JOptionPane.YES_OPTION) {
                setDtmCart();
                items.clear();
                qty = 0;
                total = 0.0d;
                lblTQnty.setText("0");
                lblTotal.setText("Rs. 0.00");
            }
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyReleased
        this.setDtmItems();
        if (cmbCategory.getSelectedIndex() == 0) {
            list.forEach(item -> {
                if (item.getItem_Name().toLowerCase().contains(txtId.getText().toLowerCase(Locale.ITALY))) {
                    dtmItems.addRow(new Object[]{item.getItem_Name(), String.format("%.2f", item.getUnit_price()), item.getNet_qty()});
                }
            });
        } else {
            list.forEach(item -> {
                if (item.getItem_Name().contains(txtId.getText()) && item.getCategory().equals(cmbCategory.getSelectedItem().toString())) {
                    dtmItems.addRow(new Object[]{item.getItem_Name(), String.format("%.2f", item.getUnit_price()), item.getNet_qty()});
                }
            });
        }
        if (tblItemList.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No items found");
            resetTxt();
            cmbCategoryAction(cmbCategory.getSelectedIndex());
        }
    }//GEN-LAST:event_txtIdKeyReleased

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        removeFromCart();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        if (tblCart.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No items in the cart");
        } else {
            Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            if (cmbSupplier.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Select the supplier", "", JOptionPane.ERROR_MESSAGE);
            } else {
                int supid = SupplierSQL.getSupplierID(cmbSupplier.getSelectedItem().toString());
                int grn_id = GrnSQL.addGRN(0, total, sdf.format(d), txtNote.getText(), supid, id);
                int item_id = 0;
                int net_qty = 0;
                for (int i = 0; i < tblCart.getRowCount(); i++) {
                    for (Items item : list) {
                        if (item.getItem_Name().equals(tblCart.getValueAt(i, 1))) {
                            item_id = item.getItem_id();
                            net_qty = item.getNet_qty();
                        }
                    }
                    GrnHasItemsSQL.addGrnItem(grn_id, item_id, Integer.parseInt(tblCart.getValueAt(i, 3).toString()));
                    ItemSQL.setQty(item_id, net_qty + Integer.parseInt(tblCart.getValueAt(i, 3).toString()));
                }
                //JOptionPane.showMessageDialog(this, "good received note was added successfully");
                Report r = new Report();
                r.generateReport("Grn.jrxml", null, OrientationEnum.PORTRAIT);
                initializeView(id);
            }
        }
    }//GEN-LAST:event_btnCheckoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblTQnty;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pannelCart;
    private javax.swing.JSpinner spinnerQty;
    private javax.swing.JTable tblCart;
    private javax.swing.JTable tblItemList;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNote;
    // End of variables declaration//GEN-END:variables

    public void initializeView(int id) {
        list = ItemSQL.getAllItems();
        setDtmItems();
        setDtmCart();
        resetTxt();
        this.id = id;

        cmbCategory.removeAllItems();
        cmbCategory.addItem("All Categories");

        List<String> groups = ItemSQL.getCategory();
        groups.forEach(group -> {
            cmbCategory.addItem(group);
        });

        cmbSupplier.removeAllItems();
        cmbSupplier.addItem("<Select the Supplier>");

        List<String> supplierlist = SupplierSQL.getSuppliers();
        supplierlist.forEach(group -> {
            cmbSupplier.addItem(group);
        });

        items = new ArrayList<>();
        qty = 0;
        total = 0.0d;
        lblTQnty.setText("0");
        lblTotal.setText("Rs. 0.00");
    }

    private void setDtmItems() {
        dtmItems = (DefaultTableModel) this.tblItemList.getModel();
        dtmItems.getDataVector().removeAllElements();
        dtmItems.fireTableDataChanged();
    }

    private void setDtmCart() {
        dtmCart = (DefaultTableModel) this.tblCart.getModel();
        dtmCart.getDataVector().removeAllElements();
        dtmCart.fireTableDataChanged();
    }

    private void resetTxt() {
        txtId.setText("");
    }

    private void cmbCategoryAction(int category) {
        switch (category) {
            case -1:
                break;
            case 0:
                list.forEach(item -> {
                    dtmItems.addRow(new Object[]{item.getItem_Name(), String.format("%.2f", item.getUnit_price()), item.getNet_qty()});
                });
                break;

            default:
                list.forEach(item -> {
                    if (item.getCategory().equals(cmbCategory.getSelectedItem().toString())) {
                        dtmItems.addRow(new Object[]{item.getItem_Name(), String.format("%.2f", item.getUnit_price()), item.getNet_qty()});
                    }
                });
                break;
        }
    }

    private void cmbCartAction(int category) {
        switch (category) {
            case -1:
                break;
            case 0:
                list.forEach(item -> {
                    if (item.getItem_Name().equals(tblItemList.getValueAt(tblItemList.getSelectedRow(), 0))) {
                        dtmCart.addRow(new Object[]{item.getCategory(), item.getItem_Name(), String.format("%.2f", item.getUnit_price()), spinnerQty.getValue().toString()});
                    }

                });
                break;

            default:
                list.forEach(item -> {
                    if (item.getItem_Name().equals(tblItemList.getValueAt(tblItemList.getSelectedRow(), 0)) && item.getCategory().equals(cmbCategory.getSelectedItem().toString())) {
                        dtmCart.addRow(new Object[]{item.getCategory(), item.getItem_Name(), String.format("%.2f", item.getUnit_price()), spinnerQty.getValue().toString()});
                    }
                });
                break;
        }
    }

    private void calQty() {
        qty += Integer.parseInt(spinnerQty.getValue().toString());
        lblTQnty.setText(String.valueOf(qty));
    }

    private void calTotal() {
        total += (Double) ((Integer.parseInt(spinnerQty.getValue().toString())) * (Double.parseDouble(tblItemList.getValueAt(tblItemList.getSelectedRow(), 1).toString())));
        lblTotal.setText(String.valueOf("Rs. " + total));
    }

    private void subQty() {
        qty -= Integer.parseInt(tblCart.getValueAt(tblCart.getSelectedRow(), 3).toString());
        lblTQnty.setText(String.valueOf(qty));
    }

    private void subTotal() {
        total -= (Double) ((Integer.parseInt(tblCart.getValueAt(tblCart.getSelectedRow(), 3).toString())) * (Double.parseDouble(tblCart.getValueAt(tblCart.getSelectedRow(), 2).toString())));
        lblTotal.setText(String.valueOf("Rs. " + total));
    }

    private void tblItemAction() {
        int row = tblItemList.getSelectedRow();
        if (row != -1) {
            if ((int) this.spinnerQty.getValue() == 0) {
                JOptionPane.showMessageDialog(this, "Select the quantity", "", JOptionPane.ERROR_MESSAGE);
            } else if (items.contains(tblItemList.getValueAt(row, 0).toString())) {
                JOptionPane.showMessageDialog(this, "Item is already excist");
            } else {
                cmbCartAction(cmbCategory.getSelectedIndex());
                items.add(tblItemList.getValueAt(row, 0));
                calQty();
                calTotal();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seletc item to add to cart", "", JOptionPane.ERROR_MESSAGE);
        }
        spinnerQty.setValue(0);
    }

    private void removeFromCart() {
        int arr[] = tblCart.getSelectedRows();
        if (arr.length == 0) {
            JOptionPane.showMessageDialog(this, "Select an item to remove");

        } else if (arr.length > 1) {
            JOptionPane.showMessageDialog(this, "Select  one item at a time");
            tblCart.clearSelection();
        } else if (arr.length == 1) {
            subQty();
            subTotal();
            items.remove(tblCart.getValueAt(tblCart.getSelectedRow(), 1));
            dtmCart.removeRow(tblCart.getSelectedRow());
        }
    }

}
