/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.se.ui.stock;

import com.se.ui.utils.ColorPalette;
import com.se.database.entities.Items;
import com.se.database.sql.ItemSQL;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author Gayani
 */
public class EdiItemDetailsView extends javax.swing.JInternalFrame {

    /**
     * Creates new form EdiItemDetails
     */
    private int itemId;
    private List<Items> list;
    private String eCategory;
    private String eItemName;
    private int eQty;
    private String eUPrice;
    private String eWarranty;

    public EdiItemDetailsView() {
        initComponents();
    }

    void initializeView(int itemId) {
        list = ItemSQL.getAllItems();
        this.itemId = itemId;
        display(itemId);
        btnSave.setText("OK");
        eCategory = txtCategory.getText();
        eItemName = txtName.getText();
        eQty = Integer.parseInt(spinnerQty.getValue().toString());
        eUPrice = txtPrice.getText();
        eWarranty = txtWarranty.getText();
    }

    public void display(int id) {
        list.forEach((Items items) -> {
            if (items.getItem_id() == id) {
                String category = items.getCategory();
                String item_name = items.getItem_Name();
                int net_qty = items.getNet_qty();
                double unit_price = items.getUnit_price();
                String warranty = items.getWarranty();
                txtCategory.setText(category);
                txtName.setText(item_name);
                spinnerQty.setValue(net_qty);
                txtPrice.setText(String.valueOf(unit_price));
                txtWarranty.setText(warranty);
            }
        });
    }

    private void cmbWarrantyAction(int warranty) {

        switch (warranty) {
            case 7:
                txtWarranty.setEnabled(true);
                txtWarranty.setBorder(BorderFactory.createLineBorder(ColorPalette.BTNBORDER, 1));
                txtWarranty.setText("");
                break;
            case 0:
                txtWarranty.setEnabled(false);
                txtWarranty.setBorder(BorderFactory.createLineBorder(java.awt.Color.LIGHT_GRAY, 1));
                txtWarranty.setText("");
                break;
            default:
                txtWarranty.setEnabled(false);
                txtWarranty.setBorder(BorderFactory.createLineBorder(java.awt.Color.LIGHT_GRAY, 1));
                txtWarranty.setText((String) cmbWarranty.getSelectedItem());
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblQty = new javax.swing.JLabel();
        lblItem = new javax.swing.JLabel();
        lblWarranty = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        spinnerQty = new javax.swing.JSpinner();
        btnSave = new javax.swing.JButton();
        cmbWarranty = new javax.swing.JComboBox();
        txtWarranty = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Edit Item Details");

        lblQty.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblQty.setText("Qty");

        lblItem.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblItem.setText("Item");

        lblWarranty.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblWarranty.setText("Warranty");

        lblCategory.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblCategory.setText("Category");

        lblPrice.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblPrice.setText("Unit Price");

        txtCategory.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCategory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCategoryKeyReleased(evt);
            }
        });

        txtPrice.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPriceKeyReleased(evt);
            }
        });

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        spinnerQty.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        spinnerQty.setEnabled(false);
        spinnerQty.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerQtyStateChanged(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSave.setText("OK");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        cmbWarranty.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmbWarranty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Select the Warranty>", "3 months", "4 months", "6 months", "1 year", "2 years", "4 years", "Other" }));
        cmbWarranty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbWarrantyActionPerformed(evt);
            }
        });

        txtWarranty.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtWarranty.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtWarranty.setEnabled(false);
        txtWarranty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWarrantyKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblItem, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWarranty, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblQty, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinnerQty, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtWarranty)
                        .addComponent(txtCategory)
                        .addComponent(txtName)
                        .addComponent(txtPrice)
                        .addComponent(cmbWarranty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblItem, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblQty, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblWarranty, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbWarranty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spinnerQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(txtWarranty, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbWarrantyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbWarrantyActionPerformed
        int cmb = cmbWarranty.getSelectedIndex();
        cmbWarrantyAction(cmb);
        if (cmbWarranty.getSelectedIndex() == 0) {
            txtWarranty.setText(eWarranty);
        }
        keyAction();
    }//GEN-LAST:event_cmbWarrantyActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String categoroy = txtCategory.getText();
        String name = txtName.getText();
        int qty = (int) spinnerQty.getValue();
        double price = Double.valueOf(txtPrice.getText());
        String warranty = "";

        if (btnSave.getText().equals("OK")) {
            this.dispose();
        } else {
            if (categoroy.equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter a category!", "", JOptionPane.INFORMATION_MESSAGE);
            } else if (name.equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter a name!", "", JOptionPane.INFORMATION_MESSAGE);
            } else if (qty == 0) {
                JOptionPane.showMessageDialog(this, "Please enter the qty!", "", JOptionPane.INFORMATION_MESSAGE);
            } else if (price == 0) {
                JOptionPane.showMessageDialog(this, "Please enter the unit price!", "", JOptionPane.INFORMATION_MESSAGE);
            } else if (txtWarranty.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please select a warranty!", "", JOptionPane.INFORMATION_MESSAGE);
            } else {
                warranty = txtWarranty.getText();

                int input = JOptionPane.showConfirmDialog(this, "Do you want to update the item details?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (input == JOptionPane.YES_OPTION) {
                    ItemSQL.updateItem(itemId, categoroy, name, qty, price, warranty);
                    JOptionPane.showMessageDialog(this, "Updated successfully, please refresh the list");
                    this.dispose();
                }

            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void spinnerQtyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerQtyStateChanged
        if (Integer.parseInt(spinnerQty.getValue().toString()) < 0) {
            spinnerQty.setValue(0);
        }
        keyAction();
    }//GEN-LAST:event_spinnerQtyStateChanged

    private void txtCategoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCategoryKeyReleased
        keyAction();
    }//GEN-LAST:event_txtCategoryKeyReleased

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        keyAction();
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyReleased
        keyAction();
    }//GEN-LAST:event_txtPriceKeyReleased

    private void txtWarrantyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWarrantyKeyReleased
        keyAction();
    }//GEN-LAST:event_txtWarrantyKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbWarranty;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblWarranty;
    private javax.swing.JSpinner spinnerQty;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtWarranty;
    // End of variables declaration//GEN-END:variables

    private void keyAction() {
        if (eQty == Integer.parseInt(spinnerQty.getValue().toString()) && eCategory.equals(txtCategory.getText()) && eItemName.equals(txtName.getText()) && eUPrice.equals(txtPrice.getText()) && eWarranty.equals(txtWarranty.getText())) {
            btnSave.setText("OK");
        } else {
            btnSave.setText("Save");
        }
    }
}
