/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.se.ui.dashboard;

import com.se.database.entities.Employee;
import com.se.database.sql.EmployeeSQL;
import com.se.ui.contact.employee.EditEmployeeView;
import com.se.ui.contact.employee.EmployeeView;
import com.se.ui.contact.supplier.SupplierView;
import com.se.ui.purchase.GRNSelectorView;
import com.se.ui.sales.InSelectorView;
import com.se.ui.sales.InvoiceListView;
import com.se.ui.stock.ItemListView;
import com.se.ui.stock.ItemSelectorView;
import com.se.ui.stock.LowStockView;
import java.awt.Color;
import java.awt.Component;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Point;
import java.util.Arrays;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author BHARATHA
 */
public class DashboardView extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public DashboardView() {
        initComponents();
        //fullScreen();
        setPosition();
        setWallpaper();
    }

    private final InSelectorView inSelectorView = new InSelectorView();
    private final InvoiceListView invoiceListView = new InvoiceListView();
    private final GRNSelectorView grnSelectorView = new GRNSelectorView();
    private final ItemSelectorView itSelectorView = new ItemSelectorView();
    private final ItemListView itemListView = new ItemListView();
    private final SupplierView supplierView = new SupplierView();
    private final EmployeeView employeeView = new EmployeeView();
    private final EditEmployeeView editProfileView = new EditEmployeeView();
    private final LowStockView lowStockView = new LowStockView();

    private Employee emp;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu = new javax.swing.JPopupMenu();
        miEditProfile = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miChangeUname = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        miChangePw = new javax.swing.JMenuItem();
        jPanelFrame = new javax.swing.JPanel();
        jLayeredPane = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        DesktopPane = new javax.swing.JDesktopPane();
        lblBack = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanelWinControl = new javax.swing.JPanel();
        btnClosepnl = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        btnMinpnl = new javax.swing.JPanel();
        btnMin = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelSales = new javax.swing.JPanel();
        btnInvoice = new javax.swing.JButton();
        jPanelPurchase = new javax.swing.JPanel();
        btnGrn = new javax.swing.JButton();
        jPanelStock = new javax.swing.JPanel();
        btnItemList = new javax.swing.JButton();
        btnManage = new javax.swing.JButton();
        btnLowStock = new javax.swing.JButton();
        jPanelContact = new javax.swing.JPanel();
        btnSupplier = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        jPanelTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelAccountDetails = new javax.swing.JPanel();
        lblUName = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();

        miEditProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/se/ui/icons/PopUpMenu/EditProfile icon.png"))); // NOI18N
        miEditProfile.setText("Edit Profile");
        miEditProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                miEditProfileMouseReleased(evt);
            }
        });
        jPopupMenu.add(miEditProfile);
        jPopupMenu.add(jSeparator1);

        miChangeUname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/se/ui/icons/PopUpMenu/ChangeUName icon.png"))); // NOI18N
        miChangeUname.setText("Change User Name");
        miChangeUname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                miChangeUnameMouseReleased(evt);
            }
        });
        jPopupMenu.add(miChangeUname);
        jPopupMenu.add(jSeparator2);

        miChangePw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/se/ui/icons/PopUpMenu/ChangePW icon.png"))); // NOI18N
        miChangePw.setText("Change Passsword");
        miChangePw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                miChangePwMouseReleased(evt);
            }
        });
        jPopupMenu.add(miChangePw);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 740));
        setResizable(false);

        jPanelFrame.setPreferredSize(new java.awt.Dimension(1370, 767));
        jPanelFrame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane.setPreferredSize(new java.awt.Dimension(1366, 767));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1366, 601));

        DesktopPane.setPreferredSize(new java.awt.Dimension(1340, 569));

        lblBack.setText("jLabel2");

        DesktopPane.setLayer(lblBack, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addComponent(lblBack, javax.swing.GroupLayout.DEFAULT_SIZE, 1354, Short.MAX_VALUE)
                .addContainerGap())
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBack, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(DesktopPane);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanelWinControl.setBackground(new java.awt.Color(255, 255, 255));

        btnClosepnl.setBackground(new java.awt.Color(255, 255, 255));

        btnClose.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setText("X");
        btnClose.setToolTipText("Exit");
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCloseMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnClosepnlLayout = new javax.swing.GroupLayout(btnClosepnl);
        btnClosepnl.setLayout(btnClosepnlLayout);
        btnClosepnlLayout.setHorizontalGroup(
            btnClosepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );
        btnClosepnlLayout.setVerticalGroup(
            btnClosepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        btnMinpnl.setBackground(new java.awt.Color(255, 255, 255));

        btnMin.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        btnMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMin.setText("-");
        btnMin.setToolTipText("Minimize");
        btnMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMinMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnMinpnlLayout = new javax.swing.GroupLayout(btnMinpnl);
        btnMinpnl.setLayout(btnMinpnlLayout);
        btnMinpnlLayout.setHorizontalGroup(
            btnMinpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMin, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );
        btnMinpnlLayout.setVerticalGroup(
            btnMinpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMinpnlLayout.createSequentialGroup()
                .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelWinControlLayout = new javax.swing.GroupLayout(jPanelWinControl);
        jPanelWinControl.setLayout(jPanelWinControlLayout);
        jPanelWinControlLayout.setHorizontalGroup(
            jPanelWinControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWinControlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnMinpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClosepnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelWinControlLayout.setVerticalGroup(
            jPanelWinControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClosepnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnMinpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnInvoice.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/se/ui/icons/dashboard/invoiceIcon.png"))); // NOI18N
        btnInvoice.setText("Invoice");
        btnInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSalesLayout = new javax.swing.GroupLayout(jPanelSales);
        jPanelSales.setLayout(jPanelSalesLayout);
        jPanelSalesLayout.setHorizontalGroup(
            jPanelSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1241, Short.MAX_VALUE))
        );
        jPanelSalesLayout.setVerticalGroup(
            jPanelSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSalesLayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(btnInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane.addTab("Sales", jPanelSales);

        btnGrn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnGrn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/se/ui/icons/dashboard/grnIicon.png"))); // NOI18N
        btnGrn.setText("GRN");
        btnGrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPurchaseLayout = new javax.swing.GroupLayout(jPanelPurchase);
        jPanelPurchase.setLayout(jPanelPurchaseLayout);
        jPanelPurchaseLayout.setHorizontalGroup(
            jPanelPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPurchaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGrn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1241, Short.MAX_VALUE))
        );
        jPanelPurchaseLayout.setVerticalGroup(
            jPanelPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPurchaseLayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(btnGrn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane.addTab("Purchase", jPanelPurchase);

        btnItemList.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnItemList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/se/ui/icons/dashboard/itemListIcon.png"))); // NOI18N
        btnItemList.setText("Item List");
        btnItemList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemListActionPerformed(evt);
            }
        });

        btnManage.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/se/ui/icons/dashboard/manageIcon.png"))); // NOI18N
        btnManage.setText("Manage");
        btnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageActionPerformed(evt);
            }
        });

        btnLowStock.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnLowStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/se/ui/icons/Dashboard/lowStockIcon.png"))); // NOI18N
        btnLowStock.setText("Low Stock");
        btnLowStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLowStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelStockLayout = new javax.swing.GroupLayout(jPanelStock);
        jPanelStock.setLayout(jPanelStockLayout);
        jPanelStockLayout.setHorizontalGroup(
            jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnItemList, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLowStock, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManage, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(987, Short.MAX_VALUE))
        );
        jPanelStockLayout.setVerticalGroup(
            jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelStockLayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addGroup(jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnItemList, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLowStock, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManage, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane.addTab("Stock", jPanelStock);

        btnSupplier.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/se/ui/icons/dashboard/supplierIcon.png"))); // NOI18N
        btnSupplier.setText("Supplier");
        btnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierActionPerformed(evt);
            }
        });

        btnEmployee.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/se/ui/icons/dashboard/employeeIcon.png"))); // NOI18N
        btnEmployee.setText("Employee");
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelContactLayout = new javax.swing.GroupLayout(jPanelContact);
        jPanelContact.setLayout(jPanelContactLayout);
        jPanelContactLayout.setHorizontalGroup(
            jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContactLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1113, Short.MAX_VALUE))
        );
        jPanelContactLayout.setVerticalGroup(
            jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContactLayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane.addTab("Contact", jPanelContact);

        jPanelTitle.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setText(" Inventory Control System");

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelAccountDetails.setBackground(new java.awt.Color(255, 255, 255));

        lblUName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblUName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/se/ui/icons/dashboard/userIcon.png"))); // NOI18N
        lblUName.setIconTextGap(2);
        lblUName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblUNameMouseReleased(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(255, 255, 255));
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/se/ui/icons/dashboard/logOutIcon.png"))); // NOI18N
        btnLogOut.setToolTipText("Log Out");
        btnLogOut.setIconTextGap(0);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAccountDetailsLayout = new javax.swing.GroupLayout(jPanelAccountDetails);
        jPanelAccountDetails.setLayout(jPanelAccountDetailsLayout);
        jPanelAccountDetailsLayout.setHorizontalGroup(
            jPanelAccountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccountDetailsLayout.createSequentialGroup()
                .addComponent(lblUName, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelAccountDetailsLayout.setVerticalGroup(
            jPanelAccountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
            .addComponent(lblUName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelWinControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAccountDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelWinControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelAccountDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane))
        );

        jLayeredPane.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneLayout = new javax.swing.GroupLayout(jLayeredPane);
        jLayeredPane.setLayout(jLayeredPaneLayout);
        jLayeredPaneLayout.setHorizontalGroup(
            jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPaneLayout.setVerticalGroup(
            jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanelFrame.add(jLayeredPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 1356, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        btnClosepnl.setBackground(new Color(232, 17, 35));
        btnClose.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        btnClosepnl.setBackground(Color.WHITE);
        btnClose.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseReleased
        int input = JOptionPane.showConfirmDialog(this, "Do you want to exit from the system without logging out?", "", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (input == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnCloseMouseReleased

    private void btnMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseEntered
        btnMinpnl.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_btnMinMouseEntered

    private void btnMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseExited
        btnMinpnl.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnMinMouseExited

    private void btnMinMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseReleased
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinMouseReleased

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        int input = JOptionPane.showConfirmDialog(this, "Do you want to Log Out from the system?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (input == JOptionPane.YES_OPTION) {
            EmployeeSQL.setLoggedOut(emp.getName());
            this.dispose();
            new LogInView().setVisible(true);
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceActionPerformed
        if (emp.getRole().equals("Admin")) {
            inSelectorView.dispose();
            DashboardView.DesktopPane.remove((Component) inSelectorView);
            DashboardView.DesktopPane.add((Component) inSelectorView);
            inSelectorView.initializeView(emp.getEmp_id());
            inSelectorView.setLocation((int) ((DesktopPane.getSize().width - inSelectorView.getSize().width) / 2), (int) ((DesktopPane.getSize().height - inSelectorView.getSize().height) / 2));
            inSelectorView.setVisible(true);
        } else {
            invoiceListView.dispose();
            DashboardView.DesktopPane.remove((Component) invoiceListView);
            DashboardView.DesktopPane.add((Component) invoiceListView);
            invoiceListView.initializeView(emp.getEmp_id());
            invoiceListView.setLocation((int) ((DesktopPane.getSize().width - invoiceListView.getSize().width) / 2), (int) ((DesktopPane.getSize().height - invoiceListView.getSize().height) / 2));
            invoiceListView.setVisible(true);
        }
    }//GEN-LAST:event_btnInvoiceActionPerformed

    private void btnGrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrnActionPerformed
        grnSelectorView.dispose();
        DashboardView.DesktopPane.remove((Component) grnSelectorView);
        DashboardView.DesktopPane.add((Component) grnSelectorView);
        grnSelectorView.initializeView(emp.getRole(),emp.getEmp_id());
        grnSelectorView.setLocation((int) ((DesktopPane.getSize().width - grnSelectorView.getSize().width) / 2), (int) ((DesktopPane.getSize().height - grnSelectorView.getSize().height) / 2));
        grnSelectorView.setVisible(true);
    }//GEN-LAST:event_btnGrnActionPerformed

    private void btnItemListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemListActionPerformed
        itemListView.dispose();
        DashboardView.DesktopPane.remove((Component) itemListView);
        DashboardView.DesktopPane.add((Component) itemListView);
        itemListView.initializeView();
        itemListView.setLocation((int) ((DesktopPane.getSize().width - itemListView.getSize().width) / 2), (int) ((DesktopPane.getSize().height - itemListView.getSize().height) / 2));
        itemListView.setVisible(true);
    }//GEN-LAST:event_btnItemListActionPerformed

    private void btnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageActionPerformed
        itSelectorView.dispose();
        DashboardView.DesktopPane.remove((Component) itSelectorView);
        DashboardView.DesktopPane.add((Component) itSelectorView);
        //itSelectorView.initializeView(emp.getRole());
        itSelectorView.setLocation((int) ((DesktopPane.getSize().width - itSelectorView.getSize().width) / 2), (int) ((DesktopPane.getSize().height - itSelectorView.getSize().height) / 2));
        itSelectorView.setVisible(true);
    }//GEN-LAST:event_btnManageActionPerformed

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierActionPerformed
        supplierView.dispose();
        DashboardView.DesktopPane.remove((Component) supplierView);
        DashboardView.DesktopPane.add((Component) supplierView);
        supplierView.initializeView(emp);
        supplierView.setLocation((int) ((DesktopPane.getSize().width - supplierView.getSize().width) / 2), (int) ((DesktopPane.getSize().height - supplierView.getSize().height) / 2));
        supplierView.setVisible(true);
    }//GEN-LAST:event_btnSupplierActionPerformed

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
        employeeView.dispose();
        DashboardView.DesktopPane.remove((Component) employeeView);
        DashboardView.DesktopPane.add((Component) employeeView);
        employeeView.initializeView(emp);
        employeeView.setLocation((int) ((DesktopPane.getSize().width - employeeView.getSize().width) / 2), (int) ((DesktopPane.getSize().height - employeeView.getSize().height) / 2));
        employeeView.setVisible(true);
    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void lblUNameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUNameMouseReleased
        if (evt.getButton() == 3) {
            Point p = lblUName.getLocationOnScreen();
            jPopupMenu.show(this, (int) p.getX() + 110, (int) p.getY() + lblUName.getHeight());
        }
    }//GEN-LAST:event_lblUNameMouseReleased

    private void miEditProfileMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miEditProfileMouseReleased
        editProfileView.dispose();
        DashboardView.DesktopPane.remove((Component) editProfileView);
        DashboardView.DesktopPane.add((Component) editProfileView);
        editProfileView.initializeView(emp);
        editProfileView.setLocation((int) ((DesktopPane.getSize().width - editProfileView.getSize().width) / 2), (int) ((DesktopPane.getSize().height - editProfileView.getSize().height) / 2));
        editProfileView.setVisible(true);
    }//GEN-LAST:event_miEditProfileMouseReleased

    private void miChangeUnameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miChangeUnameMouseReleased
        uNameAction();
    }//GEN-LAST:event_miChangeUnameMouseReleased

    private void miChangePwMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miChangePwMouseReleased
        pwAction();
    }//GEN-LAST:event_miChangePwMouseReleased

    private void btnLowStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLowStockActionPerformed
        lowStockView.dispose();
        DashboardView.DesktopPane.remove((Component) lowStockView);
        DashboardView.DesktopPane.add((Component) lowStockView);
        lowStockView.setLocation((int) ((DesktopPane.getSize().width - lowStockView.getSize().width) / 2), (int) ((DesktopPane.getSize().height - lowStockView.getSize().height) / 2));
        lowStockView.setVisible(true);
    }//GEN-LAST:event_btnLowStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JLabel btnClose;
    private javax.swing.JPanel btnClosepnl;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnGrn;
    private javax.swing.JButton btnInvoice;
    private javax.swing.JButton btnItemList;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnLowStock;
    private javax.swing.JButton btnManage;
    private javax.swing.JLabel btnMin;
    private javax.swing.JPanel btnMinpnl;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAccountDetails;
    private javax.swing.JPanel jPanelContact;
    private javax.swing.JPanel jPanelFrame;
    private javax.swing.JPanel jPanelPurchase;
    private javax.swing.JPanel jPanelSales;
    private javax.swing.JPanel jPanelStock;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JPanel jPanelWinControl;
    private javax.swing.JPopupMenu jPopupMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblUName;
    private javax.swing.JMenuItem miChangePw;
    private javax.swing.JMenuItem miChangeUname;
    private javax.swing.JMenuItem miEditProfile;
    // End of variables declaration//GEN-END:variables

    public void initializeView(Employee emp) {
        this.emp = emp;
        lblUName.setText(emp.getTitle() + " " + emp.getName());
        if (emp.getRole().equals("Admin")) {
            btnManage.setVisible(true);
        } else {
            btnManage.setVisible(false);
        }
    }

    private void uNameAction() {
        try {
            boolean flag = false;
            String input = JOptionPane.showInputDialog("Enter new User Name");
            if (!input.equals("")) {
                //System.out.println(input);
                List<Employee> list = EmployeeSQL.getAllEmployee();
                for (Employee employee : list) {
                    if (employee.getUname().equals(input)) {
                        flag = true;
                        JOptionPane.showMessageDialog(this, "This user name is already used by another employer");
                    }
                }
                if (flag == false) {
                    pfActionUN(input);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Enter a User Name");
                uNameAction();
            }
        } catch (NullPointerException e) {
        }
    }

    private void pfActionUN(String input) {
        JPasswordField jpf = new JPasswordField();
        int action = JOptionPane.showConfirmDialog(this, jpf, "Enter your Password", JOptionPane.OK_CANCEL_OPTION);
        if (action == 0) {
            if (emp.getPassword().equals(new String(jpf.getPassword()))) {
                EmployeeSQL.updateUserName(emp.getEmp_id(), input.trim());
                JOptionPane.showMessageDialog(this, "User Name updated Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect Password");
                pfActionUN(input);
            }
        }
    }

    private void pwAction() {
        JPasswordField jpf1 = new JPasswordField();
        int action1 = JOptionPane.showConfirmDialog(this, jpf1, "Enter new Password", JOptionPane.OK_CANCEL_OPTION);
        if (action1 == 0) {
            if (jpf1.getPassword().length != 0) {
                JPasswordField jpf2 = new JPasswordField();
                int action2 = JOptionPane.showConfirmDialog(this, jpf2, "Re-enter new Password", JOptionPane.OK_CANCEL_OPTION);
                if (action2 == 0) {
                    if (Arrays.equals(jpf1.getPassword(), jpf2.getPassword())) {
                        jpf2Action(String.valueOf(jpf1.getPassword()));
                    } else {
                        jpf3Action(String.valueOf(jpf1.getPassword()));
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Enter a Password");
                pwAction();
            }
        }
    }

    private void jpf3Action(String input) {
        JPasswordField jpf2 = new JPasswordField();
        int action = JOptionPane.showConfirmDialog(this, jpf2, "Passwords mismatch\nRe-enter new Password", JOptionPane.OK_CANCEL_OPTION);
        if (action == 0) {
            if (input.equals(new String(jpf2.getPassword()))) {
                jpf2Action(input);
            } else {
                jpf3Action(input);
            }
        }
    }

    private void jpf2Action(String input) {
        JPasswordField jpf = new JPasswordField();
        int action = JOptionPane.showConfirmDialog(this, jpf, "Enter current Password", JOptionPane.OK_CANCEL_OPTION);
        if (action == 0) {
            if (emp.getPassword().equals(new String(jpf.getPassword()))) {
                EmployeeSQL.updatePassword(emp.getEmp_id(), input.trim());
                JOptionPane.showMessageDialog(this, "Password updated Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect Password");
                jpf2Action(input);
            }
        }
    }

    private void setPosition() {
        setLocationRelativeTo(null);
    }
    
    private void fullScreen() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
        this.setMaximizedBounds(env.getMaximumWindowBounds());
    }
    
    private void setWallpaper() {
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/se/ui/icons/Background/sebk2.jpg"));
        lblBack.setIcon(new ImageIcon(icon.getImage().getScaledInstance(1366, 569, Image.SCALE_SMOOTH)));
        //int width = ((int) GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds().width);// - 222;
        //int height = ((int) GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds().height);// - 170;// - 133;
        //jLayeredPane.setSize(width, height);
        //DesktopPane.setSize(width, height);
        //lblBack.setIcon(new ImageIcon(icon.getImage().getScaledInstance(DesktopPane.getSize().width, DesktopPane.getSize().height, Image.SCALE_SMOOTH)));
    }
}
