/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.se.ui.dashboard;

import com.se.database.entities.Employee;
import com.se.database.sql.EmployeeSQL;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;

/**
 *
 * @author BHARATHA
 */
public class LogInView extends javax.swing.JFrame {

    /**
     * Creates new form LogInView
     */
    public LogInView() {
        initComponents();
        setPosition();
        setWallpaper();
        initializeView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelLogIn = new javax.swing.JPanel();
        lblErrorMessage = new javax.swing.JLabel();
        lblUName = new javax.swing.JLabel();
        lblPw = new javax.swing.JLabel();
        txtUName = new javax.swing.JTextField();
        txtPw = new javax.swing.JPasswordField();
        btnLogIn = new javax.swing.JButton();
        lblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLogIn.setBackground(new java.awt.Color(51, 51, 51));
        jPanelLogIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 120, 212)));

        lblErrorMessage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblErrorMessage.setForeground(java.awt.Color.red);
        lblErrorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblUName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUName.setForeground(new java.awt.Color(255, 255, 255));
        lblUName.setText("User Name  :");

        lblPw.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPw.setForeground(new java.awt.Color(255, 255, 255));
        lblPw.setText("Password     :");

        txtUName.setBackground(new java.awt.Color(51, 51, 51));
        txtUName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUName.setForeground(new java.awt.Color(255, 255, 255));
        txtUName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 120, 212)));
        txtUName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtUName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtUNameMouseReleased(evt);
            }
        });

        txtPw.setBackground(new java.awt.Color(51, 51, 51));
        txtPw.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPw.setForeground(new java.awt.Color(255, 255, 255));
        txtPw.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 120, 212)));
        txtPw.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtPwMouseReleased(evt);
            }
        });
        txtPw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPwKeyReleased(evt);
            }
        });

        btnLogIn.setBackground(new java.awt.Color(0, 120, 212));
        btnLogIn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogIn.setForeground(new java.awt.Color(255, 255, 255));
        btnLogIn.setText("Log In");
        btnLogIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 120, 212)));
        btnLogIn.setContentAreaFilled(false);
        btnLogIn.setOpaque(true);
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLogInLayout = new javax.swing.GroupLayout(jPanelLogIn);
        jPanelLogIn.setLayout(jPanelLogInLayout);
        jPanelLogInLayout.setHorizontalGroup(
            jPanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogInLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelLogInLayout.createSequentialGroup()
                        .addComponent(lblUName, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUName, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                    .addGroup(jPanelLogInLayout.createSequentialGroup()
                        .addComponent(lblPw)
                        .addGroup(jPanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLogInLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(txtPw))
                            .addGroup(jPanelLogInLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanelLogInLayout.setVerticalGroup(
            jPanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogInLayout.createSequentialGroup()
                .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPw, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, 210));

        lblBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 659, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        logInAction();
//        DashboardView dbv = new DashboardView();
//        this.dispose();
//        dbv.setVisible(true);
    }//GEN-LAST:event_btnLogInActionPerformed

    private void txtUNameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUNameMouseReleased
        lblErrorMessage.setText("");
    }//GEN-LAST:event_txtUNameMouseReleased

    private void txtPwMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPwMouseReleased
        lblErrorMessage.setText("");
    }//GEN-LAST:event_txtPwMouseReleased

    private void txtPwKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPwKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            logInAction();
        }
    }//GEN-LAST:event_txtPwKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelLogIn;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblPw;
    private javax.swing.JLabel lblUName;
    private javax.swing.JPasswordField txtPw;
    private javax.swing.JTextField txtUName;
    // End of variables declaration//GEN-END:variables

    private void initializeView() {
        txtUName.setText("");
        txtPw.setText("");
    }

    private void logInAction() {
        DashboardView dbv = new DashboardView();
        String uName = txtUName.getText().toLowerCase().trim();
        String password = txtPw.getText();
        if (uName.equals("")) {
            lblErrorMessage.setText("Enter User Name");
        } else if (password.equals("")) {
            lblErrorMessage.setText("Enter password");
        } else {
            Employee emp = EmployeeSQL.getUser(uName);

            if (emp == null) {
                lblErrorMessage.setText("Invalid User Name!");
                txtUName.setText("");
                txtPw.setText("");
            } else {
                if (emp.getPassword().equals(password)) {
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                    Date date = new Date();
                    EmployeeSQL.setLoggedIn(uName, sdf.format(date));
                    dbv.initializeView(emp);
                    this.dispose();
                    dbv.setVisible(true);
                } else {
                    lblErrorMessage.setText("Incorrect Password!");
                    txtPw.setText("");
                }
            }
        }
    }
    
    private void setPosition() {
        setLocationRelativeTo(null);
    }
    
    private void setWallpaper() {
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/se/ui/icons/Background/sebk1.jpg"));
        lblBack.setIcon(new ImageIcon(icon.getImage().getScaledInstance(659, 410, Image.SCALE_SMOOTH)));
    }
}
